import { definePlugin } from "@xinit/core";

/**
 * Django — a deterministic `startproject`-style scaffold for a Python app.
 *
 * Django's own scaffolder (`django-admin startproject`) is an exec step, but this
 * plugin stays install-only and offline: it `ctx.install(["django"])` (dispatched
 * through the app's detected manager — `uv add` / `poetry add` / `pip install`)
 * and then writes the standard Django 5.2 project files verbatim, templated with
 * the chosen `projectName`. Nothing is shelled out, so every capability but
 * `install` is honestly `false`.
 *
 * File layout matches Django 5.2 `startproject` exactly:
 *
 *   manage.py
 *   <projectName>/
 *       __init__.py
 *       settings.py
 *       urls.py
 *       asgi.py
 *       wsgi.py
 *
 * `settings.py` reads `SECRET_KEY` from `DJANGO_SECRET_KEY` (seeded via
 * `ctx.setEnv` with a dev-only placeholder) and falls back to an insecure dev
 * value, so a fresh checkout runs without extra setup while production stays
 * env-driven. Migrating/running the server is left to the developer (`ctx.warn`).
 */
export default definePlugin({
  name: "django",
  displayName: "Django",
  version: "1.0.0",
  appliesTo: { framework: "django" },
  languages: ["python"],
  dependsOn: [],
  conflicts: [],
  capabilities: { install: true, exec: false, network: false },
  detect: { file: "manage.py" },
  prompts: [
    {
      id: "projectName",
      type: "text",
      message:
        "Project (settings) package name? (holds settings.py/urls.py/wsgi.py/asgi.py)",
      default: "config",
    },
  ],
  setup: (ctx, answers) => {
    const raw =
      typeof answers.projectName === "string" && answers.projectName.trim()
        ? answers.projectName.trim()
        : "config";
    // Keep it a valid Python package/identifier; fall back if the input is unusable.
    const project = /^[A-Za-z_][A-Za-z0-9_]*$/.test(raw) ? raw : "config";

    // Django itself (manager-agnostic: `uv add django`, `poetry add django`, …).
    ctx.install(["django"]);

    // Dev-only secret. `setEnv` never overwrites an existing value, and `example`
    // seeds a committed `.env.example` template alongside `.env`.
    const DEV_SECRET = "django-insecure-dev-only-change-me";
    ctx.setEnv("DJANGO_SECRET_KEY", DEV_SECRET, { example: true });

    // manage.py — created only if absent (idempotent via findOrCreate).
    const manage = ctx.findOrCreate(
      ["manage.py"],
      "manage.py",
      managePy(project),
    );
    // findOrCreate only records a write when the file is missing; when it exists
    // it is left intact. Nothing else to do for manage.py.
    void manage;

    // The project (settings) package.
    ctx.addFile(`${project}/__init__.py`, "");
    ctx.addFile(`${project}/settings.py`, settingsPy(project, DEV_SECRET));
    ctx.addFile(`${project}/urls.py`, urlsPy(project));
    ctx.addFile(`${project}/asgi.py`, asgiPy(project));
    ctx.addFile(`${project}/wsgi.py`, wsgiPy(project));

    ctx.warn(
      "Run 'python manage.py migrate' then 'python manage.py runserver'.",
    );
  },
});

const DOCS = "5.2";

function managePy(project: string): string {
  return `#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys


def main():
    """Run administrative tasks."""
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "${project}.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
`;
}

function settingsPy(project: string, devSecret: string): string {
  return `"""
Django settings for ${project} project.

Generated by 'django-admin startproject' using Django ${DOCS}.

For more information on this file, see
https://docs.djangoproject.com/en/${DOCS}/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/${DOCS}/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/${DOCS}/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in the environment for anything other than local dev.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "${devSecret}")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "${project}.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "${project}.wsgi.application"


# Database
# https://docs.djangoproject.com/en/${DOCS}/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/${DOCS}/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/${DOCS}/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/${DOCS}/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/${DOCS}/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
`;
}

function urlsPy(project: string): string {
  return `"""
URL configuration for ${project} project.

The \`urlpatterns\` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/${DOCS}/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path("", views.home, name="home")
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path("", Home.as_view(), name="home")
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path("blog/", include("blog.urls"))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]
`;
}

function asgiPy(project: string): string {
  return `"""
ASGI config for ${project} project.

It exposes the ASGI callable as a module-level variable named \`\`application\`\`.

For more information on this file, see
https://docs.djangoproject.com/en/${DOCS}/howto/deployment/asgi/
"""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "${project}.settings")

application = get_asgi_application()
`;
}

function wsgiPy(project: string): string {
  return `"""
WSGI config for ${project} project.

It exposes the WSGI callable as a module-level variable named \`\`application\`\`.

For more information on this file, see
https://docs.djangoproject.com/en/${DOCS}/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "${project}.settings")

application = get_wsgi_application()
`;
}
